/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domen.AbstractObject;
import domen.Konobar;
import domen.Pice;
import domen.Racun;
import domen.StavkaRacuna;
import domen.Sto;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.StavkeTableModel;

/**
 *
 * @author elezs
 */
public class NewBillFrm extends javax.swing.JFrame {

    /**
     * Creates new form NewBillFrom
     */
    private Sto sto;
    private Konobar ulogovani;
    private StavkeTableModel stm;
    private Racun racun;
    private double iznos = 0;
    private JFrame parent;
    boolean unet = false;

    public NewBillFrm() {
        initComponents();
    }

    public NewBillFrm(Sto s, Konobar k, JFrame parent) {
        initComponents();
        ulogovani = k;
        sto = s;
        racun = new Racun(0, 0, ulogovani, sto, new ArrayList<>(), 0);
        this.parent = parent;
        try {
            fixForm();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(NewBillFrm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    NewBillFrm(Sto sto, Konobar ulogovani, BillsFrm aThis, Racun r) {
        initComponents();
        this.ulogovani = ulogovani;
        this.sto = sto;
        racun = r;
        racun.setKonobar(ulogovani);
        this.parent = parent;
        try {
            fixUpdateForm();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(NewBillFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLblKonobar = new javax.swing.JLabel();
        jLblSto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfIznos = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddStavka = new javax.swing.JButton();
        btnRemoveStavka = new javax.swing.JButton();
        btnSaveBill = new javax.swing.JButton();
        jcbPica = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        naplatiBtn = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Konobar:");

        jLabel2.setText("Sto:");

        jLblKonobar.setText("jLabel3");

        jLblSto.setText("jLabel3");

        jLabel3.setText("Iznos:");

        jtfIznos.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavka racuna"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnAddStavka.setText("Dodaj stavku");
        btnAddStavka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStavkaActionPerformed(evt);
            }
        });

        btnRemoveStavka.setText("Obrisi stavku");
        btnRemoveStavka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStavkaActionPerformed(evt);
            }
        });

        btnSaveBill.setText("Sacuvaj racun");
        btnSaveBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBillActionPerformed(evt);
            }
        });

        jLabel4.setText("Pice:");

        naplatiBtn.setText("Naplati");
        naplatiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naplatiBtnActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSaveBill))
                            .addComponent(naplatiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddStavka, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(btnRemoveStavka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnNazad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblSto)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jtfIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jcbPica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLblKonobar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLblKonobar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLblSto)
                    .addComponent(jLabel3)
                    .addComponent(jtfIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbPica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnAddStavka)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveStavka)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveBill)
                        .addGap(18, 18, 18)
                        .addComponent(naplatiBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNazad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStavkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStavkaActionPerformed
        // TODO add your handling code here:
        Pice p = (Pice) jcbPica.getSelectedItem();

        stm.dodajStavkuRacuna(p);
        racun.setStavkeRacuna(stm.getListStavki());
//        iznos = Integer.parseInt(jtfIznos.getText());
        iznos = stm.getRacun().getIznos();
        jtfIznos.setText(iznos + "");
        JOptionPane.showMessageDialog(this, "Stavka je uspesno dodata");
    }//GEN-LAST:event_btnAddStavkaActionPerformed

    private void btnRemoveStavkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStavkaActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if (index != -1) {
            Pice p = stm.getListStavki().get(index).getPice();
            iznos -= p.getCena();
            jtfIznos.setText(iznos + "");
            stm.obrisiStavkuRacuna(index);
            JOptionPane.showMessageDialog(this, "Stavka je uspesno obrisana");
        } else {
            JOptionPane.showMessageDialog(this, "Morate odabrati stavku za brisanje");
        }
    }//GEN-LAST:event_btnRemoveStavkaActionPerformed

    private void btnSaveBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBillActionPerformed
        // TODO add your handling code here:
        if (racun.getStavkeRacuna().isEmpty() || racun.getStavkeRacuna() == null) {
            JOptionPane.showMessageDialog(this, "Morate uneti stavku racuna");
            return;
        } else {
            try {
                racun.setIznos(iznos);
                racun.setSto(sto);
                Racun r = Controller.getControllerInstance().createBill(racun);
                r.setKonobar(ulogovani);
                racun = r;
                sto.getDnevniRacuni().add(racun);
                JOptionPane.showMessageDialog(this, "Uspesno ste kreirali racun");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Kreiranje racuna nije uspelo!");
                Logger.getLogger(NewBillFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.setVisible(false);
//        parent.setVisible(true);
        BillsFrm bf = new BillsFrm(sto, ulogovani, racun);
        bf.setVisible(true);
    }//GEN-LAST:event_btnSaveBillActionPerformed

    private void naplatiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naplatiBtnActionPerformed
        try {
            // TODO add your handling code here:
            if(racun.getStavkeRacuna() == null || racun.getStavkeRacuna().isEmpty() || stm.getListStavki().isEmpty()){
                JOptionPane.showMessageDialog(parent, "Unesite stavke racuna pre naplate!");
            }else{
                sto.setZauzet(false);
                Controller.getControllerInstance().updateTable(sto);

                racun.setPlacen(1);

                Racun r = Controller.getControllerInstance().createBill(racun);
                racun = r;
                JOptionPane.showMessageDialog(this, "Uspesno izvrsena naplata");
                this.setVisible(false);
                BillsFrm bf = new BillsFrm(sto, ulogovani);
                bf.setVisible(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(NewBillFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_naplatiBtnActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        if (racun.getPlacen() == 0) {
            int option = JOptionPane.showConfirmDialog(this, "Da li zelite da ostavite racun neplacenim?");
            if (option == JOptionPane.YES_OPTION) {
                this.setVisible(false);
                sto.setZauzet(true);
                BillsFrm bf = new BillsFrm(sto, ulogovani, racun);
                bf.setVisible(true);
            } else if (option == JOptionPane.NO_OPTION) {
                this.setVisible(false);
//        parent.setVisible(true);
                sto.setZauzet(false);
                BillsFrm bf = new BillsFrm(sto, ulogovani, racun);
                bf.setVisible(true);
            }
        }

    }//GEN-LAST:event_btnNazadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBillFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBillFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBillFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBillFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBillFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStavka;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnRemoveStavka;
    private javax.swing.JButton btnSaveBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblKonobar;
    private javax.swing.JLabel jLblSto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<Pice> jcbPica;
    private javax.swing.JTextField jtfIznos;
    private javax.swing.JButton naplatiBtn;
    // End of variables declaration//GEN-END:variables

    private void fixForm() throws Exception {
        jLblKonobar.setText(ulogovani.getName());
        jLblSto.setText(sto.getStoID() + "");
        List<StavkaRacuna> stavke = new ArrayList<>();
        fillComboBox();
        stm = new StavkeTableModel(racun);
        jTable1.setModel(stm);
        racun.setKonobar(ulogovani);
    }

    private void fillComboBox() throws Exception {
        List<AbstractObject> pica = Controller.getControllerInstance().getDrinks();
        jcbPica.setModel(new DefaultComboBoxModel(pica.toArray()));
    }

    public Racun getRacun() {
        return racun;
    }

    private void fixUpdateForm() throws Exception {
        jLblKonobar.setText(ulogovani.getName());
        jLblSto.setText(sto.getStoID() + "");
//        List<StavkaRacuna> stavke = racun.getStavkeRacuna();
        fillComboBox();
        stm = new StavkeTableModel(racun);
        jTable1.setModel(stm);
        iznos = racun.getIznos();
        jtfIznos.setText(racun.getIznos() + "");
        racun.setKonobar(ulogovani);
    }

}
