/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domen.AbstractObject;
import domen.Konobar;
import domen.Sto;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Shape;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.geom.Arc2D;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.TablesTableModel;

/**
 *
 * @author elezs
 */
public class TablesFrm extends javax.swing.JFrame {

    /**
     * Creates new form TablesFrm
     */
    List<AbstractObject> tables;
    private JFrame thisFrame;
    private Konobar ulogovani;
    TablesTableModel ttm;

    public TablesFrm(Konobar k) {
        initComponents();
        ulogovani = k;
        thisFrame = this;
        try {
            fixTables();
        } catch (Exception ex) {
            Logger.getLogger(TablesFrm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTables = new javax.swing.JTable();
        btnAddBill = new javax.swing.JButton();
        btnAddTable = new javax.swing.JButton();
        btnDeleteTable = new javax.swing.JButton();
        btnAllRevenue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pregled svih stolova");

        jTableTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTableTables);

        btnAddBill.setText("Unesi racun");
        btnAddBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBillActionPerformed(evt);
            }
        });

        btnAddTable.setText("Dodaj sto");
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });

        btnDeleteTable.setText("Obrisi sto");
        btnDeleteTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTableActionPerformed(evt);
            }
        });

        btnAllRevenue.setText("Napravi presek stanja");
        btnAllRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllRevenueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteTable)
                        .addGap(18, 18, 18)
                        .addComponent(btnAllRevenue)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddBill, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTable)
                    .addComponent(btnAddBill)
                    .addComponent(btnDeleteTable)
                    .addComponent(btnAllRevenue))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBillActionPerformed
        // TODO add your handling code here:
        int row = jTableTables.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Odaberite sto za koji zelite da unesete racun.");
        } else {
            Sto s = (Sto) tables.get(row);
            BillsFrm bf = new BillsFrm(s, ulogovani);
            bf.setVisible(true);
            this.setVisible(false);

        }
    }//GEN-LAST:event_btnAddBillActionPerformed

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTableActionPerformed
        try {
            // TODO add your handling code here:
            Sto sto = new Sto(0, 0);
            Sto noviSto = Controller.getControllerInstance().createTable(sto);
            if(noviSto != null){
                ttm.getTables().add(noviSto);
                ttm.fireTableDataChanged();
                JOptionPane.showMessageDialog(this, "Sistem je kreirao sto");
            }else{
                JOptionPane.showMessageDialog(this, "Sistem nije kreirao sto");
            }
        } catch (Exception ex) {
            Logger.getLogger(TablesFrm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }
        
    }//GEN-LAST:event_btnAddTableActionPerformed

    private void btnDeleteTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTableActionPerformed
        // TODO add your handling code here:
        int index = jTableTables.getSelectedRow();
        Sto sto = (Sto) ttm.getTables().get(index);
        if(index == -1){
            JOptionPane.showMessageDialog(this, "Morate izabrati sto za brisanje!");
            return;
        }else{
            int option = JOptionPane.showConfirmDialog(this, "Brisanjem stola, brisete i sve racune za dati sto. Da li zelite da nastavite?");
            if(option == JOptionPane.YES_OPTION){
                try {
                    Sto s = Controller.getControllerInstance().deleteTable(sto);
                    ttm.removeTable(s);
                    ttm.fireTableDataChanged();
                } catch (Exception ex) {
                    Logger.getLogger(TablesFrm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                return;
            }
        }
    }//GEN-LAST:event_btnDeleteTableActionPerformed

    private void btnAllRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllRevenueActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Ovim cete resetovati sve stolove i racune i dobiti presek danasnjeg dana. Da li zelite da nastavite?");
        if(option == JOptionPane.YES_OPTION){
            try {
                String poruka = Controller.getControllerInstance().resetTables();
                fixTables();
                JOptionPane.showMessageDialog(this, poruka);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(TablesFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            return;
        }
    }//GEN-LAST:event_btnAllRevenueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablesFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TablesFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBill;
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnAllRevenue;
    private javax.swing.JButton btnDeleteTable;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTables;
    // End of variables declaration//GEN-END:variables

    private void fixTables() throws Exception {
        tables = Controller.getControllerInstance().getTables();
        ttm = new TablesTableModel(tables);
        jTableTables.setModel(ttm);
    }
}
