/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import domen.Konobar;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author elezs
 */
public class UserPageFrm extends javax.swing.JFrame {

    /**
     * Creates new form UserPageFrm
     */
    private Konobar ulogovani;
    private Frame parent;
    public UserPageFrm() {
        initComponents();
    }

    UserPageFrm(Konobar k, Frame parent, boolean modal) {
        this.parent = parent;
        initComponents();
        ulogovani = k;
        fixForm(ulogovani);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTables = new javax.swing.JMenu();
        jmiShowTables = new javax.swing.JMenuItem();
        jMenuDrinks = new javax.swing.JMenu();
        jmiShowDrinks = new javax.swing.JMenuItem();
        jmiNewDrink = new javax.swing.JMenuItem();
        jMenuUser = new javax.swing.JMenu();
        jmiLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Korisnicka strana");

        jMenuTables.setText("Stolovi");

        jmiShowTables.setText("Prikaz stolova");
        jmiShowTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiShowTablesActionPerformed(evt);
            }
        });
        jMenuTables.add(jmiShowTables);

        jMenuBar1.add(jMenuTables);

        jMenuDrinks.setText("Pica");

        jmiShowDrinks.setText("Prikaz pica");
        jmiShowDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiShowDrinksActionPerformed(evt);
            }
        });
        jMenuDrinks.add(jmiShowDrinks);

        jmiNewDrink.setText("Unos pica");
        jmiNewDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewDrinkActionPerformed(evt);
            }
        });
        jMenuDrinks.add(jmiNewDrink);

        jMenuBar1.add(jMenuDrinks);

        jMenuUser.setText("Ime Korisnika");

        jmiLogout.setText("Izloguj se");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jMenuUser.add(jmiLogout);

        jMenuBar1.add(jMenuUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNewDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewDrinkActionPerformed
        // TODO add your handling code here:
        NewDrinkFrm ndf = new NewDrinkFrm();
        ndf.setVisible(true);
    }//GEN-LAST:event_jmiNewDrinkActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        try {
            // TODO add your handling code here:
            String poruka = Controller.getControllerInstance().logOutUser();
            JOptionPane.showMessageDialog(this, poruka);
            parent.setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            Logger.getLogger(UserPageFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void jmiShowTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiShowTablesActionPerformed
        // TODO add your handling code here:
        TablesFrm tf = new TablesFrm(ulogovani);
        tf.setVisible(true);
    }//GEN-LAST:event_jmiShowTablesActionPerformed

    private void jmiShowDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiShowDrinksActionPerformed
        // TODO add your handling code here:
        DrinksFrm df = new DrinksFrm(this, true);
        df.setVisible(true);
    }//GEN-LAST:event_jmiShowDrinksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPageFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPageFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDrinks;
    private javax.swing.JMenu jMenuTables;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiNewDrink;
    private javax.swing.JMenuItem jmiShowDrinks;
    private javax.swing.JMenuItem jmiShowTables;
    // End of variables declaration//GEN-END:variables

    private void fixForm(Konobar k) {
        jMenuUser.setText(k.getName());
    }
}
